### ISSUE TITLE
Chunked image

### ISSUE THREAD

**Issue by okomarov** [Sbte/fix_matlab_eps#5]
Thanks for supporting python 3! 

When trying on a flattened `ribbon()` figure, I get the following result:

![capture](https://cloud.githubusercontent.com/assets/3731173/21081585/0d7c715e-bfc2-11e6-855a-ffd618463902.PNG)

The following [ribbons.zip](https://github.com/Sbte/fix_matlab_eps/files/644591/ribbons.zip) contains the `ribbons.fig` to reproduce the image above. 

I have Inkscape 0.91 r13725 (Jan 30 2015)  and Ghostscript 9.19, but I get the following error if I try to open t with Ghostscript:

```
Error: /typecheck in --moveto--
Operand stack:
   --nostringval--
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval-
-   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   fa
lse   1   %stopped_push   1967   1   3   %oparray_pop   1966   1   3   %oparray_
pop   --nostringval--   1950   1   3   %oparray_pop   1836   1   3   %oparray_po
p   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringv
al--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:1194/1684(ro)(G)--   --dict:2/20(G)--   --dict:82/200(L)--   --dict:33
/50(L)--
Current allocation mode is local
Last OS error: No such file or directory
Current file position is 131017
MiKTeX GPL Ghostscript 9.19: Unrecoverable error, exit code 1
```

The script does work on the example you provide!

**Comment by Sbte** [comment]
Can you provide the eps file that Matlab generates? I don't always have access to Matlab.

Also, the trick I use only works for images with patches of a constant color, like for instance contour plots. I'm not sure if it also works for these ribbons, since there is no constant color in there. I also got it to work for the colorbar, however, so I can have a look.

**Comment by okomarov** [comment]
Thanks for looking into that, here's the .eps
[ribbons_eps.zip](https://github.com/Sbte/fix_matlab_eps/files/658884/ribbons_eps.zip)

**Comment by Sbte** [comment]
I finally got to look into it, and fixed some issues. Now your image seems to render correctly, but there are still horizontal white lines. I'm not sure yet how to get rid of those. They are harder since the gradients do not have a uniform color.

**Comment by Dev-iL** [comment]
Hi @Sbte,
I'm having an issue with similar symptoms - in my case half of the image just disappears...

Consider the following figure (the large images were plotted using `imshow`; [download link](http://s000.tinyupload.com/index.php?file_id=98958104316435376670 "I can't seem to be able to upload a .zip to GitHub :\")):
![image](https://user-images.githubusercontent.com/6509619/27145058-e262c506-513c-11e7-822f-41c28cb6194c.png)

However, after applying `fix_matlab_eps` it becomes:
![image](https://user-images.githubusercontent.com/6509619/27145047-d557bd6c-513c-11e7-8fdf-7ac196492f3a.png)

Any idea what can be done about this?

I'm using Inkscape 0.92.1 r15371, GhostScript 9.20, Win7 x64, MATLAB R2017a.

---------
P.S. 
I tried creating programmatically an example figure that demonstrates this problem, but there seems to be an issue in Inkscape, where it cannot correctly import [an image](https://github.com/Sbte/fix_matlab_eps/files/1075382/output.pdf) created like this:

```matlab
function eps_demo
hF = figure('Position',[544,597,750,291]); hA = gobjects(2,1);
hA(1) = subplot(1,2,1); imshow(7*uint8(magic(6)));
hA(2) = subplot(1,2,2); p = hA(2).Position;
imshow(uint8(repmat(28*magic(3),[2,2]))); colorbar(hA(2)); caxis([0 intmax('uint8')])
hA(2).Position = p;
%% Exporting:
fName = 'output.pdf'; % or .eps
% saveas(hF,fName);
export_fig(fName,'-transparent');
```

P.S. 2
I'm using a slightly different version of the code, found on [my own branch](https://github.com/Dev-iL/fix_matlab_eps), but where the business logic is unchanged.

**Comment by Sbte** [comment]
@Dev-iL For some reason I never got a notification of your reply. Sorry for that.

Your issue is completely different from the original issue. Your issue is that the images you have look, in terms of code, the same as a colorbar. The colorbar, for some reason, is split up into two parts of which you need only one. Therefore I remove the first.

For your problem, I could fix this by checking if the `cairo_image` part of the code is the same. However, if I do that it will still not work in case you have two of the exact same images next to each other. Since this will make the code a lot more complicated (and more prone to bugs), your use case is nowhere near the original use case (contour plots) and it does not completely solve the issue (multiple of the same images) I think I do not want to fix this problem.

If you have only one image, it's probably easiest to just manually remove the first part of the colorbar, and make sure you make the remaining part square instead of triangular.
